[package]
name = "wallet"
version = "0.1.0"
authors = ["Concordium AG <contact@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pairing = "0.15"
ff = "0.5"
rand = "=0.7"
hex = "0.3"
serde = "1.0"
serde_json = "1.0"
failure = "0.1"
chrono = "0.4"
ed25519-dalek = "=1.0.0-pre.3"
byteorder = "1.3"
either = "1.5"
sha2 = "0.8"
libc = "0.2"

[dependencies.crypto_common]
path = "../crypto_common"
version = "0"

[dependencies.curve_arithmetic]
path = "../curve_arithmetic"
version = "0"

[dependencies.elgamal]
path = "../elgamal"
version = "0"

[dependencies.dodis_yampolskiy_prf]
path = "../dodis_yampolskiy_prf"
version = "0"

[dependencies.id]
path = "../id"
version = "0"

[dependencies.pedersen_scheme]
path = "../pedersen_scheme"
version = "0"

[dependencies.ps_sig]
path = "../ps_sig"
version = "0"

[dependencies.eddsa_ed25519]
path = "../eddsa_ed25519"
version = "0"

[dependencies.ffi_helpers]
path = "../ffi_helpers"
version = "0"

[lib]
name = "wallet"
crate-type = ["rlib", "cdylib", "staticlib"]
path = "src/lib.rs"
