[package]
name = "random_oracle"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3      = "0.8"
itertools = "0.8"
rand    = "0.4"
rand_core = "0.5"

[dependencies.curve_arithmetic]
path = "../curve_arithmetic"
version = "0"

[lib]
name = "random_oracle"
crate-type = ["rlib", "staticlib", "cdylib" ]
