[package]
name = "simple_id_client"
version = "0.1.0"
authors = ["Concordium"]
edition = "2018"

[dependencies]
clap = "2.33"
dialoguer = "0.5"
pairing = "0.15"
ff = "0.5"
rand = "=0.7"
hex = "0.3"
serde = "1.0"
serde_json = "1.0"
failure = "0.1"
chrono = "0.4"
ed25519-dalek = "=1.0.0-pre.3"
byteorder = "1.3"
either = "1.5"
rouille = "3.0"


[dependencies.crypto_common]
path = "../crypto_common"
version = "0"

[dependencies.curve_arithmetic]
path = "../curve_arithmetic"
version = "0"

[dependencies.elgamal]
path = "../elgamal"
version = "0"

[dependencies.dodis_yampolskiy_prf]
path = "../dodis_yampolskiy_prf"
version = "0"

[dependencies.id]
path = "../id"
version = "0"

[dependencies.pedersen_scheme]
path = "../pedersen_scheme"
version = "0"

[dependencies.ps_sig]
path = "../ps_sig"
version = "0"

[dependencies.eddsa_ed25519]
path = "../eddsa_ed25519"
version = "0"

[dependencies.ec_vrf_ed25519_sha256]
path = "../ec_vrf_ed25519_sha256"
version = "0"

# To generate keys for bakers only
[dependencies.aggregate_sig]
path = "../aggregate_sig"
version = "0"

[lib]
name = "client_server_helpers"
path = "src/lib.rs"
