[package]
name = "simple_id_client"
version = "0.1.0"
authors = ["Concordium"]
edition = "2018"

[dependencies]
clap = "2.33"
dialoguer = "0.4"
ff = "0.4"
rand = "0.4"
hex = "0.3"
serde_json = "1.0"
failure = "0.1"
chrono = "0.4"
ed25519-dalek = "1.0.0-pre.1"
byteorder = "1.3"

rouille = "3.0"

[dependencies.pairing]
git = "ssh://git@gitlab.com:22/Concordium/rust/external/pairing.git"
branch = "master"

[dependencies.curve_arithmetic]
path = "../curve_arithmetic"
version = "0"

[dependencies.elgamal]
path = "../elgamal"
version = "0"

[dependencies.dodis_yampolskiy_prf]
path = "../dodis_yampolskiy_prf"
version = "0"

[dependencies.id]
path = "../id"
version = "0"

[dependencies.pedersen_scheme]
path = "../pedersen_scheme"
version = "0"

[dependencies.ps_sig]
path = "../ps_sig"
version = "0"

[dependencies.eddsa_ed25519]
path = "../eddsa_ed25519"
version = "0"

[dependencies.ec_vrf_ed25519_sha256]
path = "../ec_vrf_ed25519_sha256"
version = "0"


[lib]
name = "client_server_helpers"
path = "src/lib.rs"
