name:                concordium-base
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

custom-setup:
  dependencies:
    - base  >= 4.7
    - Cabal >= 2.2
    - directory >= 1.3

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         See README

default-extensions:
- RecordWildCards
- LambdaCase
- TupleSections
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving

flags:
  static:
    description: Use static linking.
    manual: True
    default: False

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- base16-bytestring >= 0.1.1.6
- unordered-containers >= 0.2
- containers >= 0.6
- hashable >= 1.2
- mtl >= 2.2
- transformers >= 0.5
- cereal >= 0.5
- microlens-platform >=0.3
- microlens >=0.3
- time >= 1.8
- aeson >= 1.4.2
- ghc-prim >= 0.5.3
- vector >= 0.12
- pqueue >= 1.4.1
- prettyprinter >= 1.2
- random >= 1.1
- template-haskell >= 2.14
- persistent >= 2.10
- text >= 1.2
- QuickCheck >= 2.12
- scientific >= 0.3.2
- deepseq >= 1.4
- primitive >= 0.7
# binary is used by aeson and we need for a couple of instances. cereal should
# be used for everything else.
- binary >= 0.8

library:
  source-dirs: haskell-src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Werror=missing-fields
    - -Werror=missing-methods
    - -Wredundant-constraints
    - -fno-ignore-asserts

  extra-libraries:
    - ecvrf
    - sha_2
    - eddsa_ed25519
    - ffi_helpers
    - id
    - aggregate_sig
    - encrypted_transfers


executables:
  generate-update-keys:
    main: Main.hs
    source-dirs: generate-update-keys
    ghc-options:
      - -Wall
      - -Wcompat
      - -Werror=missing-fields
      - -Werror=missing-methods
      - -Wredundant-constraints
      - -fno-ignore-asserts
    dependencies:
      - concordium-base
      - aeson-pretty >= 0.8
      - filepath >= 1.4
      - optparse-applicative >= 0.15

tests:
  test:
    main:                Spec.hs
    source-dirs:         haskell-tests
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -Wno-deprecations

    when:
      - condition: flag(static)
        ld-options:
          - -static

      - condition: "!os(windows)"
        ghc-options: -dynamic

    dependencies:
    - concordium-base
    - hspec >= 2.6
    - QuickCheck >= 2.12
    - hspec-expectations >= 0.8
    - containers
    - random
    - HUnit >= 1.6

benchmarks:
  ed25519-perf:
    main: haskell-bench/Ed25519Perf.hs
    dependencies:
      - concordium-base
      - criterion >= 1.5
    when:
      - condition: "!os(windows)"
        ghc-options: -dynamic

  ed25519dlog-perf:
    main: haskell-bench/Ed25519DlogPerf.hs
    dependencies:
      - concordium-base
      - criterion >= 1.5
    when:
      - condition: "!os(windows)"
        ghc-options: -dynamic

  bls-perf:
    main: haskell-bench/BlsPerf.hs
    dependencies:
      - concordium-base
      - criterion >= 1.5
    when:
      - condition: "!os(windows)"
        ghc-options: -dynamic

  sha256-perf:
    main: haskell-bench/SHA256Perf.hs
    dependencies:
      - concordium-base
      - criterion >= 1.5
    when:
      - condition: "!os(windows)"
        ghc-options: -dynamic

  verify-credential-perf:
    main: haskell-bench/VerifyCredentialPerf.hs
    dependencies:
      - concordium-base
      - criterion >= 1.5
    when:
      - condition: "!os(windows)"
        ghc-options: -dynamic
