name:                globalstate-types
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         See README

default-extensions:
- RecordWildCards
- LambdaCase
- TupleSections
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving

flags:
  static:
    description: Use static linking.
    manual: True
    default: False
  disable-smart-contracts:
    description: Disable transactions related to smart contracts
    manual: True
    default: False

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- base16-bytestring >= 0.1.1.6
- unordered-containers >= 0.2
- containers >= 0.6
- hashable >= 1.2
- mtl >= 2.2
- transformers >= 0.5
- cereal >= 0.5
- microlens-platform >=0.3
- microlens >=0.3
- time >= 1.8
- concordium-crypto
- aeson >= 1.4.2
- ghc-prim >= 0.5.3
- vector >= 0.12
- pqueue >= 1.4.1
- prettyprinter >= 1.2
- random >= 1.1
- template-haskell >= 2.14
- persistent >= 2.10
- text >= 1.2
- QuickCheck >= 2.12

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Werror=missing-fields
    - -Werror=missing-methods
    - -Wredundant-constraints
    - -fno-ignore-asserts
  when:
      condition: flag(disable-smart-contracts)
      cpp-options:
        - -DDISABLE_SMART_CONTRACTS

tests:
  types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    - -Wall

    when:
      condition: flag(static)
      ld-options:
      - -static

    dependencies:
    - globalstate-types
    - concordium-crypto
    - hspec >= 2.6
    - QuickCheck >= 2.12
    - hspec-expectations >= 0.8
    - containers
    - random
