name:                globalstate-types
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         See README

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- unordered-containers >= 0.2
- containers >= 0.6
- hashable >= 1.2
- mtl >= 2.2
- transformers >= 0.5
- cereal >= 0.5

- concordium-crypto

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Werror=missing-fields
    - -Wredundant-constraints
    - -fno-ignore-asserts

