[workspace]

members=[
   "curve_arithmetic",
   "ec_vrf_ed25519_sha256",
   "eddsa_ed25519",
   "sha_2",
   "dodis_yampolskiy_prf",
   "pedersen_scheme",
   "elgamal",
   "ps_sig",
   "sigma_protocols",
   "id",
   "ffi_helpers",
   "simple_id_client",
   "secret_sharing",
]

