[workspace]

members=[
   "curve_arithmetic",
   "ec_vrf_ed25519_sha256",
   "eddsa_ed25519",
   "sha_2",
   "dodis_yampolskiy_prf",
   "pedersen_scheme",
   "pedersen_scheme2",
   "elgamal",
   "sigma_protocols",
   "ps_sig" ]

