[package]
name = "concordium-sc-base"
version = "0.1.0"
authors = ["Concordium <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Reduce code size, at the cost of performance in allocation heavy-code.
wee_alloc="0.4.5"
byteorder = "1.3"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
# Don't unwind on panics, just trap.
panic = "abort"
