[package]
name = "wasmer-runner"
version = "0.1.0"
authors = ["Concordium <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
structopt = "0.3"
hex = "0.4"
serde_json="1.0.56"

[dependencies.wasmer-interp]
version = "0.1"
path = "../wasmer-interp"

[dev-dependencies]
criterion = "0.3"
wasmer-runtime-core="0.17.1"

[dependencies.contracts-common]
version = "0.1"
path = "../contracts-common"
features = ["derive-serde"]

[dev-dependencies.wasmer-runtime]
version="0.17.1"
default-features = false
features = ["default-backend-cranelift"]

[[bench]]
name = "wasm"
harness = false
