[package]
name = "wasmer-runner"
version = "0.1.0"
authors = ["Concordium <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime="0.17.1"
clap = "2.33"
structopt = "0.3"
hex = "0.4"

[dependencies.wasmer-interp]
path = "../wasmer-interp"