[package]
name = "curve_arithmetic"
version = "0.1.0"
authors = ["bassel <bassel.mannaa@gmail.com>"]
edition = "2018"

[dependencies]
ff = "0.4"
rand    = "0.4"
failure = "0.1"
libc = "0.2"
byteorder = "1.3"
bytes = "0.4.12"
sha2 = "0.8"

[dependencies.pairing]
git = "ssh://git@gitlab.com:22/Concordium/rust/external/pairing.git"
branch = "master"

[dependencies.ffi_helpers]
path = "../ffi_helpers"

[dependencies.crypto_common]
path = "../crypto_common"

[dependencies.crypto_common_derive]
path = "../crypto_common_derive"

[lib]
name = "curve_arithmetic"
crate-type = ["rlib", "staticlib", "cdylib"]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "hash_bench"
harness = false
