[package]
name = "curve_arithmetic"
version = "0.1.0"
authors = ["bassel <bassel.mannaa@gmail.com>"]
edition = "2018"

[dependencies]
ff = "0.4"
rand    = "0.4"
failure = "0.1"
libc = "0.2"
byteorder = "1.3"
bytes = "0.4.12"
sha2 = "0"

[dependencies.pairing]
path = "../pairing"

[dependencies.ffi_helpers]
path = "../ffi_helpers"

[lib]
name = "curve_arithmetic"
crate-type = ["rlib", "staticlib", "cdylib"]
