[package]
name = "curve_arithmetic"
version = "0.1.0"
authors = ["bassel <bassel.mannaa@gmail.com>"]
edition = "2018"

[dependencies]
pairing = "0.14"
rand    = "0.4"
failure = "0.1"
libc = "0.2"
byteorder = "1.3"

[dependencies.ffi_helpers]
path = "../ffi_helpers"

[dependencies.common]
path = "../common"

[lib]
name = "curve_arithmetic"
crate-type = ["rlib", "staticlib", "cdylib"]
