[package]
name = "context-test"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]

std = ["concordium-std/std"]

[dependencies]
byteorder = "1.3"

[dependencies.concordium-std]
git = "https://github.com/Concordium/concordium-std.git"
branch = "expose-policy"
# path = "../../../../../concordium-std/concordium-std"
default-features = false

[dependencies.sha2]
version = "0.9.1"
default-features = false

[dependencies.hex]
version = "0.4.2"
default-features = false

[lib]
crate-type = ["cdylib", "rlib"]
