[workspace]
resolver = "3"

members = [
   "contracts-common/concordium-contracts-common",
   "contracts-common/concordium-contracts-common-derive",
   "wasm-chain-integration",
   "wasm-transform",
   "wasm-test",
   #"wasm-fuzz", # not currently added, since it does not compile, add it when compile is fixed
]

