[package]
name = "cargo-concordium"
version = "0.1.0"
authors = ["Concordium <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
structopt = "0.3"
hex = "0.4"
serde_json="1.0.56"
cargo_toml = "0.8.1"
anyhow = "1.0.33"

[features]

[dependencies.wasmer-interp]
version = "0.1"
path = "../wasmer-interp"

[dev-dependencies]
criterion = "0.3"

[dependencies.contracts-common]
version = "0.1"
path = "../contracts-common"
features = ["derive-serde"]
