[package]
name = "cargo-concordium"
version = "1.0.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license-file = "../LICENSE-APACHE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
structopt = "0.3"
hex = "0.4"
serde = "1.0"
serde_json="1.0.56"
cargo_toml = "0.8.1"
anyhow = "1.0.33"
ansi_term = "0.12"

[features]

[dependencies.wasm-transform]
path = "../wasm-transform"
version = "0"

[dependencies.wasm-chain-integration]
version = "0.1"
path = "../wasm-chain-integration/"

[dev-dependencies]
criterion = "0.3"

[dependencies.concordium-contracts-common]
version = "0.4.1"
path = "../concordium-contracts-common"
features = ["derive-serde", "std"]
