[package]
name = "every-example"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license = "MPL-2.0"
license-file = "../../../LICENSE-MPL-2.0"

[dependencies]
context-test = {path = "../context-test"}
counter = {path = "../counter"}
erc20 = {path = "../erc20"}
escrow = {path = "../escrow"}
rate-limited = {path = "../rate-limited"}
fib = {path = "../fib"}
lockup = {path = "../lockup"}
simple-game = {path = "../simple-game"}
use-all-host-functions = {path = "../use-all-host-functions"}

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
# Don't unwind on panics, just trap.
# panic = "abort"
