name:                mpfr-test
version:             0.1.0.0
# license:             
author:              "Felix Wiemuth"
maintainer:          "Felix Wiemuth <fw@concordium.com>"
# copyright:           

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         See README.md

dependencies:
- base >= 4.7 && < 5
- containers >0.5.9.1
- hspec >= 2.5
- QuickCheck >= 2.10
- hmpfr >= 0.4.4

executables:
  MPFRTest:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts

