name:                mpfr-test
version:             0.1.0.0
license:             "MPL-2.0"
license-file:        "../LICENSE"
author:              "Concordium AG"
maintainer:          "developers@concordium.com"
# copyright:           

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         See README.md

dependencies:
- base >= 4.7 && < 5
- containers >0.5.9.1
- QuickCheck >= 2.10
- async >= 2.2.1
- hmpfr >= 0.4.4

executables:
  MPFRTest:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts

