[package]
name = "rate-limited"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]

std = ["concordium-sc-base/std"]
build-schema = []

[dependencies]
byteorder = "1.3"

[dependencies.concordium-sc-base]
path="../../concordium-sc-base"
default-features = false

[dev-dependencies.concordium-sc-base]
path="../../concordium-sc-base"
features = ["std"] # std is needed because testing depends on std.

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
# Don't unwind on panics, just trap.
# panic = "abort"
