[package]
name = "eddsa_ed25519"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

[dependencies]
ed25519-dalek = "1.0.0-pre.1"
curve25519-dalek = "1"
rand          = "0.6.5"
serde         = "1"
sha2      = "0"
failure   = "0"

[dev-dependencies]
criterion = "0.2"

[lib]
name = "eddsa_ed25519"
crate-type = ["rlib", "staticlib", "cdylib"]
