version: '3'
services:
  identity-provider-service:
    image: concordium/identity-provider-service:0.4.0-0
    environment:
      - MODE=identity-provider-service
      - IDENTITY_PROVIDER_SERVICE_PORT=7011
      - ANONYMITY_REVOKERS=/anonymity_revokers.json
      - IDENTITY_PROVIDER=/identity_provider.json
      - GLOBAL_CONTEXT=/global.json
      - RETRIEVE_BASE=https://id-service.eu.staging.concordium.com
      - ID_VERIFICATION_URL=http://localhost:7012/api/verify
      - ID_VERIFICATION_QUERY_URL=http://identity-verifier:7012/api/verify
      - WALLET_PROXY_BASE=https://wallet-proxy.testnet.concordium.com
    ports:
      - "7011:7011"
  identity-verifier:
    image: concordium/identity-provider-service:0.4.0-0
    environment:
      - MODE=identity-verifier
      - IDENTITY_VERIFIER_PORT=7012
      - IDENTITY_PROVIDER_URL=http://identity-provider-service:7011
    ports:
      - "7012:7012"
