[package]
name = "wasmer-interp"
version = "0.1.0"
authors = ["Concordium <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime="0.17.1"

[lib]
crate-type = ["cdylib", "rlib"]
