[package]
name = "sha_2"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

[dependencies]
sha2 = "0.8"

[lib]
name = "sha_2"
crate-type = ["rlib", "staticlib", "cdylib"]
