[package]
name = "counter"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3"

[dependencies.concordium_sc_base]
path="../../concordium_sc_base"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
# Don't unwind on panics, just trap.
panic = "abort"

