[package]
name = "secret_sharing"
version = "0.1.0"
authors = ["Concordium AG"]

[dependencies]
pairing = "0.14"
failure       = "0.1"
rand    = "0.4"
rand_core = "0.5"
clear_on_drop = "0.2"
serde = "1.0"
libc  = "0.2"

[dependencies.curve_arithmetic]
path = "../curve_arithmetic"
version = "0"

[dev-dependencies]
criterion = "0.2"

[lib]
name = "secret_sharing"
crate-type = ["rlib", "staticlib", "cdylib"]
