[package]
name = "sigma_protocols"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

[dependencies]
pairing = "0"
sha2      = "0"
failure       = "0"
rand    = "0.4"
rand_core = "0.3.0"
clear_on_drop = "0"
serde         = "1"
libc = "0.2.58"
byteorder = "1.3"

[dependencies.curve_arithmetic]
path = "../curve_arithmetic"
version = "0" 

[dependencies.ffi_helpers]
path = "../ffi_helpers"
version = "0"

[lib]
name = "sigma_protocols"
crate-type = ["rlib", "staticlib", "cdylib" ]
