name: Build and test smart-contracts workspace

# This job runs rustfmt and clippy linting,
# and then it runs cargo test and ./target/debug/wasm-test

on:
  push:
    branches:
        - main

  pull_request:

  workflow_dispatch: # allows manual trigger

jobs:

  "wat-wasm-consistency":
    name: Ensure consistency between wat and wasm files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install WABT
        run: sudo apt-get update && sudo apt-get -y install wabt
      - name: Check consistency
        run: ./.diff-wat-wasm.sh

  "lint_fmt":
    name: smart-contracts fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        working-directory: smart-contracts
        run: |
          rustup component add rustfmt
          cargo fmt -- --color=always --check

  "lint_doc":
    name: smart-contracts doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Docs
        working-directory: smart-contracts
        run: |
          rustup component add rust-docs
          RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features

  "lint_clippy":
    name: smart-contracts clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Clippy
        working-directory: smart-contracts
        run: |
          rustup component add clippy
          cargo clippy --color=always --all-targets --all-features -- -D warnings

  "cargo_test":
    name: smart-contracts test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        working-directory: smart-contracts
        run: |
          cargo test --all-features

  "wasm-core-spec_cargo_test":
    name: wasm-core-spec cargo:test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        working-directory: smart-contracts/wasm-test
        run: |
          cargo build
          ../target/debug/wasm-test --dir ../testdata/wasm-spec-test-suite/core/

  contracts_common_check:
    name: Check on concordium-contracts-common for x64 and wasm32 and different features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo check
        working-directory: smart-contracts/contracts-common/concordium-contracts-common
        run: |
          # Try different feature combinations on default (x86 linux) target
          cargo check --no-default-features
          cargo check --no-default-features --features std
          cargo check --no-default-features --features derive-serde
          cargo check --features std,derive-serde

          # Try different feature combinations on wasm32v1 target
          rustup target add wasm32v1-none
          cargo check --target wasm32v1-none --no-default-features --features smart-contract 
          cargo check --target wasm32v1-none --no-default-features --features smart-contract,wasm-test
          cargo check --target wasm32v1-none --no-default-features --features smart-contract,build-schema

  wasm_chain_integration_check:
    name: Check on wasm-chain-integration for different features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo check
        working-directory: smart-contracts/wasm-chain-integration
        run: |
          # Try different feature combinations
          cargo check
          cargo check --features enable-ffi
          cargo check --features display-state
          cargo check --features async
          cargo check --all-features
