name: Release Concordium Base Derive

on:

  workflow_dispatch: # allows manual trigger

  push:

    ## TODO - remove me later
    branches:
      - feature/COR1786-release-git-action-concordium-base-derive

    tags:
      - releases/concordium_base_derive/*

env:
  TAG: ${{ github.ref_name }}

jobs:

  ## Concordium Base Derive Release Build
  concordium-base-derive-release:
    name: concordium-base-derive:release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # Set the default working directory to concordium_base_derive
        working-directory: rust-src/concordium_base_derive

    ## TODO - bring this back later for main
    #environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Validate that the tag version matches the version in Cargo.toml
      - name: validate tag version has correct matching tag
        run: |
          echo "Validating tag version $TAG matches expected version from Cargo.toml"
          pwd
          EXPECTED_VERSION_FROM_CARGO=$(yq .package.version ./Cargo.toml)
          TAG_VERSION_NUMBER=${TAG##releases/concordium_base_derive/}
          
          # Check if the tag version number matches the expected version from Cargo.toml
          if [ "$TAG_VERSION_NUMBER" != "$EXPECTED_VERSION_FROM_CARGO" ]; then
            echo "version tagged: $TAG_VERSION_NUMBER  does not match cargo version: $EXPECTED_VERSION_FROM_CARGO. Exiting."
            exit 1
          else
            echo "Tag version number matches expected version from Cargo.toml. Proceeding with release."
          fi

      # Publish to crates.io
      - name: Publish to crates.io
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "Publishing Concordium Base Derive to crates.io for version: $TAG_VERSION"
          pwd
          #cargo publish --token $CARGO_TOKEN --locked