[package]
name = "lockup"
version = "0.1.0"
authors = ["Concordium AG <info@concordium.com>"]
edition = "2018"

[features]
default = ["std"]

std = ["concordium-sc-base/std"]

[dependencies]
byteorder = "1.3"

[dependencies.concordium-sc-base]
path="../../concordium-sc-base"
default-features = false

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
