[package]
name = "ffi_helpers"
version = "0.1.0"
authors = ["Concordium AG <developers@concordium.com>"]
edition = "2018"
license-file = "../../LICENSE"

[dependencies]
libc = "0.2"

[lib]
name = "ffi_helpers"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib", "cdylib"]
